//Exporta las claves de escenas
export const SCENE_KEYS = Object.freeze({
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    BATTLE_SCENE: 'BATTLE_SCENE',
    WORLD_SCENE: 'WORLD_SCENE',
    TITLE_SCENE: 'TITLE_SCENE',
    OPTION_SCENE: 'OPTION_SCENE',
    TEST_SCENE: 'TEST_SCENE',
    MONSTER_PARTY_SCENE: 'MONSTER_PARTY_SCENE',
    MONSTER_DETAILS_SCENE: 'MONSTER_DETAILS_SCENE',
    INVENTORY_SCENE: 'INVENTORY_SCENE',
    NPC_DIALOG_SCENE: 'NPC_DIALOG_SCENE',
})